apiVersion: v1
kind: Pod
metadata:
   name: multi-container
   labels:
     project: roboshop
     purpose: multi-container-demo
spec:
  containers:
  - name: mysql
    image: mysql
  - name: almalinux
    image: almalinux
    command: ["sleep","1000"]
